### ISSUE TITLE
Feature: User can create a moodboard

### ISSUE THREAD

**Issue by brandon-au** [brandon-au/mubo-Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to create and name a moodboard

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create and name a new moodboard to upload images to

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109652009/200992301-8e1ed4a9-68ec-4cc4-8c9a-cd49cac88c49.png)
![image](https://user-images.githubusercontent.com/109652009/200992442-0408a606-a881-4f96-a89a-6fb188eb673f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to create a moodboard table
- [ ] Update `data.sql` to add dummy data

### ☁️ Server Tasks

- [ ] Update `server/index.js` to make a GET request to moodboard table
- [ ] Update `server/index.js` to make a POST request to moodboard table
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a homepage to view moodboards
- [ ] Create a modal to create a moodboard
- [ ] Create a component to create a moodboard
- [ ] Update component to show moodboard on homepage
- [ ] Add media queries for mobile (1 column) and desktop (3 columns)
- [ ] Clicking logo at top redirects to homepage

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
